# Project information
site_name: Zabbix Book
site_url: https://trikke76.github.io/Zabbix-Book
site_author: Patrik Uytterhoeven

# Repository
repo_name: trikke76
repo_url: https://github.com/trikke76/Zabbix-Book
edit_uri: edit/master/docs
docs_dir: docs

# Navigation
nav:
  - Welcome: 'index.md'
  - 'Getting started':
    - installation/Requirements.md
    - installation/installing-zabbix.md
  - 'The basics':
    - configuration/Dashboard.md
    - configuration/zabbix-users.md
    - configuration/zabbix-hosts.md
    - configuration/zabbix-hostgroups.md
    - configuration/zabbix-items.md
    - configuration/zabbix-interfaces.md
    - configuration/zabbix-macros.md
    - configuration/zabbix-dataflow.md
    - configuration/zabbix-agent.md
  - 03-Detecting and managing problems.md
  - 04-Taking action when problems come.md
  - 05-Managing Permissions.md
  - 06-Visualising our problems.md
  - 07-Automating configuration.md
  - 08-VMWare monitoring.md
  - 09-Monitoring websites.md
  - 10-Monitoring SNMP,IPMI and JAVA.md
  - 11-Monitoring with Proxies.md
  - 12-Securing Zabbix.md
  - 13-Maintaining Zabbix.md
  - 14-Monitoring Windows.md
  - 15-Zabbix API.md

theme:
   name: material
   font:
     text: IBM Plex Sans
     code: IBM Plex Mono
   icon:
     logo: material/library
   features:
     # - navigation.tabs
     - navigation.instant
     - navigation.expand
   palette:
     scheme: default
     primary: blue
     accent: blue

# Plugins
plugins:
  - search
  - with-pdf: #add only if you like to build a pdf file
      author: Patrik Uytterhoeven
      copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
      #
      #cover: false
      #back_cover: true
      cover_title: Zabbix 7 Monitoring
      cover_subtitle: Enterprise Monitoring With Zabbix
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: chrome-headless
      #
      output_path: ../zabbix-7-book.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

# Customization
# TBD

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.progressbar
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
